'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Download, ExternalLink, FileText, Play } from 'lucide-react';
type Page='home'|'graphic'|'pgvg'|'website'|'3d'|'aigc';
const items:{id:Page;label:string;note:string;className:string;emoji:string}[]=[
{id:'graphic',label:'Graphic Design',note:'Logo · Social · Editorial',className:'obj-ipad',emoji:'✦'},
{id:'pgvg',label:'PGVG',note:'Photography · Videography',className:'obj-camera',emoji:'●'},
{id:'website',label:'Website',note:'UI/UX · Creative Development',className:'obj-imac',emoji:'↗'},
{id:'3d',label:'3D Modelling',note:'Booth · Spatial Design',className:'obj-booth',emoji:'◇'},
{id:'aigc',label:'AIGC',note:'AI Generated Video Content',className:'obj-robot',emoji:'◡'}];
const graphicImages=Array.from({length:27},(_,i)=>`/portfolio/graphic/images/graphic-${String(i+1).padStart(2,'0')}${i>=9&&i<=15?'.avif':'.png'}`);
const photos=Array.from({length:5},(_,i)=>`/portfolio/pgvg/photos/photo-${String(i+1).padStart(2,'0')}.png`);
const filmVideos=Array.from({length:4},(_,i)=>({video:`/portfolio/pgvg/videos/film-${String(i+1).padStart(2,'0')}.mp4`,poster:`/portfolio/pgvg/videos/film-${String(i+1).padStart(2,'0')}.jpg`}));
const webVideos=['1826 Studio','Hola Hola','Interactive Website'].map((title,i)=>({title,video:`/portfolio/website/website-${String(i+1).padStart(2,'0')}.mp4`,poster:`/portfolio/website/website-${String(i+1).padStart(2,'0')}.jpg`}));
const modelVideos=['MIXUE Booth','Workshop Booth'].map((title,i)=>({title,video:`/portfolio/3d/model-${String(i+1).padStart(2,'0')}.mp4`,poster:`/portfolio/3d/model-${String(i+1).padStart(2,'0')}.jpg`}));
const aiVideos=Array.from({length:9},(_,i)=>({video:`/portfolio/aigc/ai-video-${String(i+1).padStart(2,'0')}.mp4`,poster:`/portfolio/aigc/ai-video-${String(i+1).padStart(2,'0')}.jpg`}));

export default function Home(){
 const [page,setPage]=useState<Page>('home');const [ready,setReady]=useState(false);const [mouse,setMouse]=useState({x:0,y:0});const [format,setFormat]=useState('Desktop');const [model,setModel]=useState('Clay');
 useEffect(()=>{const hash=location.hash.slice(1) as Page;if(items.some(x=>x.id===hash))setPage(hash);const t=setTimeout(()=>setReady(true),350);return()=>clearTimeout(t)},[]);
 const go=(next:Page)=>{setPage(next);setReady(false);setTimeout(()=>setReady(true),40);history.replaceState(null,'',next==='home'?'#':`#${next}`)};
 return <main className={`site page-${page} ${ready?'page-ready':''}`} onMouseMove={e=>setMouse({x:(e.clientX/innerWidth-.5)*16,y:(e.clientY/innerHeight-.5)*12})}>
  <header className="topbar"><button className="brand" onClick={()=>go('home')}><span>J</span> JOSEPHINE</button><nav>{items.map(x=><button className={page===x.id?'active':''} key={x.id} onClick={()=>go(x.id)}>{x.label}</button>)}</nav><a className="available" href="/portfolio/resume/josephine-resume.pdf" target="_blank"><i/> Resume</a></header>
  <div className="view-key" key={page}>{page==='home'&&<Studio mouse={mouse} go={go}/>} {page==='graphic'&&<Graphic/>} {page==='pgvg'&&<PGVG/>} {page==='website'&&<Web format={format} setFormat={setFormat}/>} {page==='3d'&&<Models model={model} setModel={setModel}/>} {page==='aigc'&&<Lab/>}</div>
  <button className="mascot" onClick={()=>go(page==='home'?'aigc':'home')}><span>•ᴗ•</span><i>{page==='home'?'Need a tour?':'Back home'}</i></button>
 </main>;
}
function Studio({mouse,go}:{mouse:{x:number,y:number};go:(p:Page)=>void}){return <section className="studio is-ready"><div className="intro"><p>WELCOME TO MY CREATIVE SPACE</p><h1>Ideas live<br/><em>on my desk.</em></h1></div><div className="room" style={{transform:`translate3d(${mouse.x}px,${mouse.y}px,0)`}}><div className="wall-note">Make<br/>curious<br/>things.</div><div className="shelf"><span/><span/><span/></div><div className="desk-back"/><div className="desk"><div className="desk-edge"/><div className="leg left"/><div className="leg right"/></div>{items.map(x=><button key={x.id} className={`studio-object ${x.className}`} onClick={()=>go(x.id)}><span className="object-shape"><b>{x.emoji}</b></span><span className="object-tip"><small>{x.label}</small>{x.note}<ArrowUpRight size={14}/></span></button>)}<a className="book" href="/portfolio/resume/josephine-resume.pdf" target="_blank"><span>ABOUT<br/>ME</span></a></div><div className="explore"><span>01 / 06</span><p>Hover the objects to explore</p><i>↓</i></div></section>}
function Title({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy:string}){return <div className="section-title"><p>{index} / 06 &nbsp; {kicker}</p><h1>{title}</h1><span>{copy}</span></div>}
function Graphic(){return <section className="subpage graphic-page real-work-page"><Title index="02" kicker="SELECTED + ARCHIVE" title="Graphic Design" copy="Logo, social media, brochures, banners, presentations and company profiles."/><div className="asset-count">31 WORKS</div><div className="real-grid graphic-grid">{graphicImages.map((src,i)=><a href={src} target="_blank" className={`real-card card-${i%5}`} key={src}><img src={src} alt={`Graphic design work ${i+1}`} loading="lazy"/><span>{i<2?'Brochure':i<5?'Banner & bunting':i<7?'Logo design':i<9?'Social poster':'Social media carousel'} <b>{String(i+1).padStart(2,'0')}</b></span></a>)}</div><div className="document-row"><DocumentCard title="FansTag AI Company Profile" cover="/portfolio/graphic/documents/company-profile-01-cover.png" file="/portfolio/graphic/documents/company-profile-01.pdf"/><DocumentCard title="YooSnap Proposal" cover="/portfolio/graphic/documents/company-profile-02-cover.png" file="/portfolio/graphic/documents/company-profile-02.pdf"/></div><h2 className="archive-heading">Presentation Design</h2><div className="video-grid compact">{[1,2].map(i=><VideoCard key={i} title={`AI Presentation ${String(i).padStart(2,'0')}`} video={`/portfolio/graphic/videos/presentation-${String(i).padStart(2,'0')}.mp4`} poster={`/portfolio/graphic/videos/presentation-${String(i).padStart(2,'0')}.jpg`}/>)}</div></section>}
function PGVG(){return <section className="subpage pgvg-page real-work-page"><Title index="03" kicker="PHOTOGRAPHY + VIDEOGRAPHY" title="Photo & Video" copy="A collection of photography studies and moving-image projects."/><h2 className="archive-heading light">Photography</h2><div className="photo-strip">{photos.map((src,i)=><a href={src} target="_blank" key={src}><img src={src} alt={`Photography work ${i+1}`} loading="lazy"/><span>PHOTO 0{i+1}</span></a>)}</div><h2 className="archive-heading light">Videography</h2><div className="video-grid dark-grid">{filmVideos.map((x,i)=><VideoCard key={x.video} title={`Film Study 0${i+1}`} {...x}/>)}</div></section>}
function Web({format,setFormat}:{format:string;setFormat:(x:string)=>void}){return <section className="subpage web-page real-work-page"><Title index="04" kicker="RECORDED EXPERIENCES" title="Web Experiences" copy="Three responsive projects shown through real interaction recordings."/><div className="device-toggle">{['Desktop','Tablet','Mobile'].map(x=><button className={format===x?'active':''} onClick={()=>setFormat(x)} key={x}>{x}</button>)}</div><div className={`web-showcase ${format.toLowerCase()}`}>{webVideos.map(x=><VideoCard key={x.video} {...x}/>)}</div></section>}
function Models({model,setModel}:{model:string;setModel:(x:string)=>void}){return <section className={`subpage models-page real-work-page model-mode-${model.toLowerCase()}`}><Title index="05" kicker="BOOTH MODELLING" title="3D Modelling" copy="Two spatial booth-design projects presented as full walkthroughs."/><div className="model-tabs">{['Wireframe','Clay','Final'].map(x=><button className={model===x?'active':''} onClick={()=>setModel(x)} key={x}>{x}</button>)}</div><div className="model-video-grid">{modelVideos.map(x=><VideoCard key={x.video} {...x}/>)}</div></section>}
function Lab(){return <section className="subpage lab-page real-work-page"><Title index="06" kicker="AI GENERATED VIDEO CONTENT" title="AIGC Video" copy="Nine AI-generated moving-image experiments across characters, worlds and visual storytelling."/><div className="aigc-intro"><span>09 FILMS</span><p>AI image generation · Video generation · Editing · Sound</p></div><div className="ai-video-grid">{aiVideos.map((x,i)=><VideoCard key={x.video} title={`AI Generated Film ${String(i+1).padStart(2,'0')}`} {...x}/>)}</div></section>}
function VideoCard({title,video,poster}:{title:string;video:string;poster?:string}){return <article className="video-card"><div className="video-frame"><video controls playsInline preload="metadata" poster={poster}><source src={video} type="video/mp4"/></video><span className="video-badge"><Play size={11} fill="currentColor"/> PLAY</span></div><footer><h3>{title}</h3><a href={video} target="_blank" aria-label={`Open ${title}`}><ExternalLink size={15}/></a></footer></article>}
function DocumentCard({title,cover,file}:{title:string;cover:string;file:string}){return <a className="document-card" href={file} target="_blank"><img src={cover} alt={`${title} cover`}/><span><FileText size={15}/><b>{title}</b><Download size={15}/></span></a>}
