'use client';
import { useEffect, useState } from 'react';
import WebsiteGallery from './website-gallery';
import PGVGGallery from './pgvg-gallery';
import { ArrowUpRight, ChevronLeft, ChevronRight, ExternalLink, Play } from 'lucide-react';
type Page='home'|'about'|'graphic'|'pgvg'|'website'|'3d'|'aigc';
const items:{id:Page;label:string;note:string;className:string;emoji:string}[]=[
{id:'graphic',label:'Graphic Design',note:'Poster · Logo · Profile · PPT · Print',className:'obj-ipad',emoji:'✦'},
{id:'pgvg',label:'PGVG',note:'Photography · Videography',className:'obj-camera',emoji:'●'},
{id:'website',label:'Website',note:'Live Website · Case Study',className:'obj-imac',emoji:'↗'},
{id:'3d',label:'3D Modelling',note:'Booth · Spatial Design',className:'obj-booth',emoji:'◇'},
{id:'aigc',label:'AIGC',note:'Commercial · Short Video',className:'obj-robot',emoji:'◡'}];
const path=(n:number)=>`/works/graphic/graphic-${String(n).padStart(2,'0')}.webp`;
const posterGroups=[
 {title:'GWTT',kind:'Poster',images:[path(8)]},{title:'ScentPur',kind:'Poster',images:[path(9)]},
 {title:'Crocs — Jelly Cat',kind:'Social Media Carousel',images:[path(10),path(11)]},
 {title:'TP News',kind:'Social Media Carousel',images:Array.from({length:9},(_,i)=>path(i+12))},
 {title:'FansTag AI',kind:'Social Media Carousel',images:Array.from({length:7},(_,i)=>path(i+21))},
];
const logoWorks=[
 {title:'1826 Studio',kind:'Logo Design',images:[path(6)]},
 {title:'HY Fried Station',kind:'Logo Design',images:[path(7)]},
];
const photos=['100Plus','Alcohol','Bird','Flower','Fragrance'].map((title,i)=>({title,src:`/works/photos/photo-${String(i+1).padStart(2,'0')}.webp`}));
const films=['Hola Hola Banana — Daily Routine','Superbstone','Superbstone Beauty Shot','Superbstone Q&A'].map((title,i)=>({title,video:`/works/films/film-${String(i+1).padStart(2,'0')}.mp4`,poster:`/works/films/film-${String(i+1).padStart(2,'0')}.jpg`}));
const models=['MIXUE Booth','CROCS Booth'].map((title,i)=>({title,video:`/works/models/model-${String(i+1).padStart(2,'0')}.mp4`,poster:`/works/models/model-${String(i+1).padStart(2,'0')}.jpg`}));
const commercial=['AIGC System','Pellucid — Children','Pellucid — Elder','Pellucid','Solura — Testimonial','Solura','获客系统'].map((title,i)=>({title,video:`/works/aigc/ai-video-${String(i+1).padStart(2,'0')}.mp4`,poster:`/works/aigc/ai-video-${String(i+1).padStart(2,'0')}.jpg`,aspect:i===0||i===6?'landscape':'portrait'}));
const shortVideos=['Jora 01','Jora 02'].map((title,i)=>({title,video:`/works/aigc/ai-video-${String(i+8).padStart(2,'0')}.mp4`,poster:`/works/aigc/ai-video-${String(i+8).padStart(2,'0')}.jpg`,aspect:'short'}));

export default function Home(){
 const [page,setPage]=useState<Page>('home');const [ready,setReady]=useState(false);const [mouse,setMouse]=useState({x:0,y:0});const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{const hash=location.hash.slice(1) as Page;if(hash==='about'||items.some(x=>x.id===hash))setPage(hash);const t=setTimeout(()=>setReady(true),350);return()=>clearTimeout(t)},[]);
 useEffect(()=>{document.body.classList.toggle('mobile-menu-open',menuOpen);return()=>document.body.classList.remove('mobile-menu-open')},[menuOpen]);
 const go=(next:Page)=>{setPage(next);setMenuOpen(false);setReady(false);setTimeout(()=>setReady(true),40);history.replaceState(null,'',next==='home'?'#':`#${next}`)};
 return <main className={`site page-${page} ${ready?'page-ready':''}`} onMouseMove={e=>setMouse({x:(e.clientX/innerWidth-.5)*16,y:(e.clientY/innerHeight-.5)*12})}>
  <header className="topbar"><button className="brand" onClick={()=>go('home')}><span>J</span><b className="brand-desktop">JOSEPHINE</b><b className="brand-mobile">Mah Jie Yi</b></button><button className="menu-toggle" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?'×':'☰'}</button><nav className={menuOpen?'open':''}><button className={page==='about'?'active':''} onClick={()=>go('about')}>About Me</button>{items.map(x=><button className={page===x.id?'active':''} key={x.id} onClick={()=>go(x.id)}>{x.label}</button>)}<a className="mobile-contact-link" href="https://wa.link/gp0ucn" target="_blank" rel="noopener noreferrer"><i/> Contact</a></nav><a className="available" href="https://wa.link/gp0ucn" target="_blank" rel="noopener noreferrer"><i/> Contact</a></header>
  <div className="view-key" key={page}>{page==='home'&&<Studio mouse={mouse} go={go}/>} {page==='about'&&<About/>} {page==='graphic'&&<Graphic/>} {page==='pgvg'&&<PGVG/>} {page==='website'&&<Web/>} {page==='3d'&&<Models/>} {page==='aigc'&&<Lab/>}</div>
  <button className="mascot" onClick={()=>go(page==='home'?'aigc':'home')}><span>•ᴗ•</span><i>{page==='home'?'Need a tour?':'Back home'}</i></button>
 </main>
}
function Studio({mouse,go}:{mouse:{x:number,y:number};go:(p:Page)=>void}){return <section className="studio is-ready"><div className="intro"><p>WELCOME TO MY CREATIVE SPACE</p><h1>Ideas live<br/><em>on my desk.</em></h1></div><div className="mobile-intro"><p>PORTFOLIO · 2026</p><h1>Mah Jie Yi</h1><h2>Creative Designer</h2><span>Graphic design, moving image, digital experiences and playful visual ideas.</span></div><div className="room" style={{transform:`translate3d(${mouse.x}px,${mouse.y}px,0)`}}><div className="wall-note">Make<br/>curious<br/>things.</div><div className="shelf"><span/><span/><span/></div><div className="desk-back"/><div className="desk"><div className="desk-edge"/><div className="leg left"/><div className="leg right"/></div>{items.map(x=><button key={x.id} className={`studio-object ${x.className}`} onClick={()=>go(x.id)}><span className="object-shape"><b>{x.emoji}</b></span><span className="object-tip"><small>{x.label}</small>{x.note}<ArrowUpRight size={14}/></span></button>)}<button className="book" onClick={()=>go('about')} aria-label="Open About Me scrapbook"><span>ABOUT<br/>ME</span></button><button className="mobile-about-card" onClick={()=>go('about')}><span>ABOUT<br/>ME</span><b>About Me</b><small>Introduction · Resume</small><ArrowUpRight size={16}/></button></div><div className="explore"><span>01 / 06</span><p>Hover the objects to explore</p></div></section>}
function About(){
 const [page,setPage]=useState(0);const [mobile,setMobile]=useState(false);const [tilt,setTilt]=useState({x:0,y:0});
 useEffect(()=>{const media=matchMedia('(max-width: 767px)');const sync=()=>setMobile(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
 const max=mobile?3:1;const move=(n:number)=>setPage(p=>Math.max(0,Math.min(max,p+n)));
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[mobile]);
 const panels=[
  <article className="scrap-page visual-page" key="visual"><span className="paperclip">⌇</span><span className="tape tape-a"/><div className="page-heading"><small>HELLO, I AM</small><h1>Mah Jie Yi</h1><p>Creative Designer</p></div><div className="chibi-wrap"><img src="/assets/mah-jie-yi-chibi.png" alt="Chibi illustration of Mah Jie Yi holding a tablet"/></div><blockquote>“Design with purpose,<br/>create with heart.”</blockquote><span className="sticker istj">ISTJ</span><span className="sparkle s1">✦</span><span className="sparkle s2">✧</span><span className="heart">♡</span><div className="mini-polaroid"><span>WORK IN<br/>PROGRESS</span><b>creative mode · on</b></div><p className="torn-note">Good ideas<br/>start with<br/><em>curiosity.</em></p></article>,
  <article className="scrap-page copy-page" key="about"><span className="side-tab pink">ABOUT</span><span className="tape tape-b"/><p className="script-note">a little bit about me...</p><h2>About Me</h2><div className="about-copy"><p>Hi, I am Mah Jie Yi — an ISTJ advertising graduate from Xiamen University Malaysia.</p><p>I’m a multidisciplinary creative designer working across graphic design, website development, 3D modelling, video editing, and AI-driven content.</p><p>I learn fast, adapt quickly, and enjoy turning ideas into functional, well-crafted digital outcomes.</p><p>My strengths lie in structure, precision, and execution — making creative work not only look good, but work well.</p></div><div className="skill-tags">{[['🎨','Graphic Design','pink'],['▣','Website','blue'],['◇','3D Modelling','sage'],['▸','Video Editing','yellow'],['✦','AIGC','lavender']].map(([icon,label,color])=><span className={color} key={label}><i>{icon}</i>{label}</span>)}</div><p className="meaningful">Let’s build something meaningful.</p><button className="page-curl" onClick={()=>move(1)} aria-label="Flip to resume"><small>Next:</small><b>Resume</b><ChevronRight/></button></article>,
  <article className="scrap-page resume-left" key="resume-left"><span className="side-tab blue">RESUME</span><p className="about-kicker">01 · PROFILE</p><h2>Resume</h2><p className="resume-intro">Multidisciplinary creative designer focused on visual communication, digital experience, and fast execution.</p><div className="resume-section"><h3>Education</h3><div className="timeline-item"><b>Xiamen University Malaysia</b><span>Bachelor in Advertising</span><small>2022–2026</small></div></div><div className="resume-section"><h3>Experience</h3>{[['Creative Executive','Jynx Dyrhyme','2026'],['Marketing & Brand Executive','FansTag AI','2025–2026'],['Marketing Manager Assistant','AMG Clinic','2025']].map(x=><div className="timeline-item" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></article>,
  <article className="scrap-page resume-right" key="resume-right"><span className="tape tape-c"/><p className="about-kicker">02 · TOOLKIT</p><section><h3>Skills</h3><div className="resume-pills">{['Graphic Design','Website Development','3D Modelling','Video Editing','AIGC','Social Media Planning'].map(x=><span key={x}>{x}</span>)}</div></section><section><h3>Tools</h3><p>Adobe Illustrator · Canva · WordPress · Wix · SketchUp · CapCut · AI Creative Tools</p></section><section><h3>Languages</h3><div className="language-grid">{['Mandarin','English','Malay','Cantonese'].map(x=><span key={x}>{x}</span>)}</div></section>{/* Replace this PDF in public/assets whenever the resume is updated. */}<a className="download-resume" href="/assets/Mah-Jie-Yi-Resume.pdf" target="_blank">Download Resume <ExternalLink size={16}/></a><p className="script-note bottom-note">always learning, always making ✦</p></article>
 ];
 const shown=mobile?[panels[page]]:page===0?[panels[0],panels[1]]:[panels[2],panels[3]];
return <section className={`about-scrapbook spread-${page}`} onMouseMove={e=>!mobile&&setTilt({x:(e.clientX/innerWidth-.5)*3,y:(e.clientY/innerHeight-.5)*-3})}><header className="about-page-header"><h1>About Me</h1></header><div className="book-stage"><div className="scrap-book" style={{'--tilt-x':`${tilt.y}deg`,'--tilt-y':`${tilt.x}deg`} as any}><div className="book-cover"/><div className="paper-stack left-stack"/><div className="paper-stack right-stack"/><div className={`page-spread ${page>0?'is-turned':''}`}>{shown}</div></div><div className="book-actions"><button onClick={()=>move(-1)} disabled={page===0} aria-label="Previous book page"><ChevronLeft/> Previous</button><span>{mobile?`${page+1} / 4`:page===0?'About spread':'Resume spread'}</span><button onClick={()=>move(1)} disabled={page===max} aria-label="Next book page">{page===0?'Flip page':'Next'} <ChevronRight/></button></div></div></section>
}
function Title({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy:string}){return <div className="section-title"><p>{index} / 06 &nbsp; {kicker}</p><h1>{title}</h1><span>{copy}</span></div>}
function SectionHead({number,title,copy}:{number:string;title:string;copy?:string}){return <div className="work-section-head"><span>{number}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function Graphic(){return <section className="subpage graphic-page real-work-page"><Title index="02" kicker="SIX DISCIPLINES" title="Graphic Design" copy=""/><div className="graphic-jump">{['Poster','Logo','Company Profile','PPT','Brochure','Bunting & Banner'].map((x,i)=><a key={x} href={`#graphic-${i+1}`}>{String(i+1).padStart(2,'0')} {x}</a>)}</div>
 <div id="graphic-1" className="work-section"><SectionHead number="01" title="Poster"/><div className="poster-project-grid">{posterGroups.map(x=><ImageCarousel key={x.title} {...x}/>)}</div></div>
 <div id="graphic-2" className="work-section"><SectionHead number="02" title="Logo"/><div className="poster-project-grid logo-project-grid">{logoWorks.map(x=><ImageCarousel key={x.title} {...x}/>)}</div></div>
 <div id="graphic-3" className="work-section profile-section"><SectionHead number="03" title="Company Profile"/><div className="book-grid"><FlipBook title="Yoo Media" folder="yoo-media" pages={25}/><FlipBook title="EN Proposal" folder="en-proposal" pages={47}/></div></div>
 <div id="graphic-4" className="work-section"><SectionHead number="04" title="PPT"/><div className="video-grid compact">{['企动AI 01','企动AI 02'].map((title,i)=><VideoCard key={title} title={title} video={`/works/graphic/presentation-${String(i+1).padStart(2,'0')}.mp4`} poster={`/works/graphic/presentation-${String(i+1).padStart(2,'0')}.jpg`}/>)}</div></div>
 <div id="graphic-5" className="work-section"><SectionHead number="05" title="Brochure"/><div className="poster-project-grid brochure-project-grid"><ImageCarousel title="Brochure" kind="Print Design" images={[path(1),path(2)]}/></div></div>
 <div id="graphic-6" className="work-section"><SectionHead number="06" title="Bunting & Banner"/><div className="print-grid banners">{['Compasia','FansTag AI 01','FansTag AI 02'].map((title,i)=><a href={path(i+3)} target="_blank" key={title}><img src={path(i+3)} alt={title}/><span>{title}</span></a>)}</div></div>
 </section>}
function PGVG(){return <section className="subpage pgvg-page real-work-page"><Title index="03" kicker="PHOTOGRAPHY + VIDEOGRAPHY" title="Photo & Video" copy=""/><SectionHead number="01" title="Photography"/><div className="photo-strip">{photos.map(x=><a href={x.src} target="_blank" key={x.title} aria-label={`View full ${x.title} photograph`}><img loading="lazy" src={x.src} alt={x.title}/><span>{x.title}</span></a>)}</div><SectionHead number="02" title="Videography"/><PGVGGallery projects={films}/></section>}
function Web(){return <WebsiteGallery/>}
function Models(){return <section className="subpage models-page real-work-page"><Title index="05" kicker="BOOTH MODELLING" title="3D Modelling" copy=""/><div className="model-video-grid">{models.map(x=><VideoCard key={x.title} {...x}/>)}</div></section>}
function Lab(){return <section className="subpage lab-page real-work-page"><Title index="06" kicker="AI GENERATED VIDEO CONTENT" title="AIGC Video" copy=""/><SectionHead number="01" title="Commercial Video"/><div className="ai-video-grid">{commercial.map(x=><VideoCard key={x.title} {...x}/>)}</div><SectionHead number="02" title="Short Video"/><div className="ai-video-grid short-grid">{shortVideos.map(x=><VideoCard key={x.title} {...x}/>)}</div></section>}
function ImageCarousel({title,kind,images}:{title:string;kind:string;images:string[]}){const [slide,setSlide]=useState(0);const move=(n:number)=>setSlide((slide+n+images.length)%images.length);return <article className="carousel-card"><button className="carousel-image" onClick={()=>images.length>1&&move(1)} aria-label={`Next ${title} slide`}><img loading="lazy" src={images[slide]} alt={`${title} — slide ${slide+1}`}/>{images.length>1&&<span>{slide+1} / {images.length}</span>}</button><footer><div><small>{kind}</small><h3>{title}</h3></div><div className="carousel-actions"><a href={images[slide]} target="_blank" aria-label={`View full ${title} artwork`}><ExternalLink/></a>{images.length>1&&<div className="carousel-controls"><button aria-label={`Previous ${title} slide`} onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label={`Next ${title} slide`} onClick={()=>move(1)}><ChevronRight/></button></div>}</div></footer><div className="carousel-dots">{images.map((_,i)=><button aria-label={`View ${title} slide ${i+1}`} className={i===slide?'active':''} onClick={()=>setSlide(i)} key={i}/>)}</div></article>}
function FlipBook({title,folder,pages}:{title:string;folder:string;pages:number}){const [page,setPage]=useState(1);const move=(n:number)=>setPage(Math.min(pages,Math.max(1,page+n)));const pageSrc=`/works/books/${folder}/page-${String(page).padStart(2,'0')}.jpg`;return <article className="flipbook"><div className="book-page" onClick={()=>move(1)}><a href={pageSrc} target="_blank" aria-label={`View full ${title} page ${page}`} onClick={e=>e.stopPropagation()}><img loading="lazy" src={pageSrc} alt={`${title} page ${page}`}/></a><i/></div><footer><div><small>COMPANY PROFILE</small><h3>{title}</h3></div><div className="book-controls"><button aria-label={`Previous ${title} page`} onClick={()=>move(-1)} disabled={page===1}><ChevronLeft/></button><span>{String(page).padStart(2,'0')} / {pages}</span><button aria-label={`Next ${title} page`} onClick={()=>move(1)} disabled={page===pages}><ChevronRight/></button></div></footer></article>}
function VideoCard({title,video,poster,aspect}:{title:string;video:string;poster?:string;aspect?:string}){return <article className={`video-card${aspect?` video-${aspect}`:''}`}><div className="video-frame"><video controls playsInline muted={false} preload="metadata" poster={poster}><source src={video} type="video/mp4"/></video><span className="video-badge"><Play size={11} fill="currentColor"/> PLAY</span></div><footer><h3>{title}</h3><a href={video} target="_blank" aria-label={`Open ${title}`}><ExternalLink size={15}/></a></footer></article>}
