'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, ChevronLeft, ChevronRight, Expand, Play, Send, Sparkles } from 'lucide-react';
type Page='home'|'graphic'|'pgvg'|'website'|'3d'|'aigc';
const items:{id:Page;label:string;note:string;className:string;emoji:string}[]=[
{id:'graphic',label:'Graphic Design',note:'Branding · Editorial · Campaign',className:'obj-ipad',emoji:'✦'},
{id:'pgvg',label:'PGVG',note:'Photography · Video · Visuals',className:'obj-camera',emoji:'●'},
{id:'website',label:'Website',note:'UI/UX · Creative Development',className:'obj-imac',emoji:'↗'},
{id:'3d',label:'3D Modelling',note:'Clay · Product · Spatial',className:'obj-booth',emoji:'◇'},
{id:'aigc',label:'AIGC',note:'Prompt · Image · Experiment',className:'obj-robot',emoji:'◡'}];
const projects=[['KINOKO','Brand identity','identity','01'],['NEON TEA','Campaign system','campaign','02'],['PAPER CLUB','Editorial design','editorial','03'],['MORI','Packaging','packaging','04']];

export default function Home(){
 const [page,setPage]=useState<Page>('home'); const [ready,setReady]=useState(false); const [mouse,setMouse]=useState({x:0,y:0});
 const [format,setFormat]=useState('Desktop'); const [model,setModel]=useState('Clay'); const [shot,setShot]=useState(0); const [prompt,setPrompt]=useState('A tiny dream studio floating above the clouds'); const [generated,setGenerated]=useState(false);
 useEffect(()=>{const hash=location.hash.slice(1) as Page;if(items.some(x=>x.id===hash))setPage(hash);const t=setTimeout(()=>setReady(true),350);return()=>clearTimeout(t)},[]);
 const go=(next:Page)=>{setPage(next);setReady(false);setTimeout(()=>setReady(true),40);history.replaceState(null,'',next==='home'?'#':`#${next}`)};
 return <main className={`site page-${page} ${ready?'page-ready':''}`} onMouseMove={e=>setMouse({x:(e.clientX/innerWidth-.5)*16,y:(e.clientY/innerHeight-.5)*12})}>
  <header className="topbar"><button className="brand" onClick={()=>go('home')}><span>J</span> JOSEPHINE</button><nav>{items.map(x=><button className={page===x.id?'active':''} key={x.id} onClick={()=>go(x.id)}>{x.label}</button>)}</nav><button className="available"><i/> Available</button></header>
  <div className="view-key" key={page}>
   {page==='home'&&<Studio mouse={mouse} go={go}/>} {page==='graphic'&&<Graphic/>} {page==='pgvg'&&<PGVG shot={shot} setShot={setShot}/>} {page==='website'&&<Web format={format} setFormat={setFormat}/>} {page==='3d'&&<Models model={model} setModel={setModel}/>} {page==='aigc'&&<Lab prompt={prompt} setPrompt={setPrompt} generated={generated} setGenerated={setGenerated}/>} 
  </div>
  <button className="mascot" onClick={()=>go(page==='home'?'aigc':'home')}><span>•ᴗ•</span><i>{page==='home'?'Need a tour?':'Back home'}</i></button>
 </main>;
}

function Studio({mouse,go}:{mouse:{x:number,y:number};go:(p:Page)=>void}){return <section className="studio is-ready"><div className="intro"><p>WELCOME TO MY CREATIVE SPACE</p><h1>Ideas live<br/><em>on my desk.</em></h1></div><div className="room" style={{transform:`translate3d(${mouse.x}px,${mouse.y}px,0)`}}><div className="wall-note">Make<br/>curious<br/>things.</div><div className="shelf"><span/><span/><span/></div><div className="desk-back"/><div className="desk"><div className="desk-edge"/><div className="leg left"/><div className="leg right"/></div>{items.map(x=><button key={x.id} className={`studio-object ${x.className}`} onClick={()=>go(x.id)}><span className="object-shape"><b>{x.emoji}</b></span><span className="object-tip"><small>{x.label}</small>{x.note}<ArrowUpRight size={14}/></span></button>)}<button className="book" onClick={()=>alert('About / Resume placeholder — ready for your copy and PDF.')}><span>ABOUT<br/>ME</span></button></div><div className="explore"><span>01 / 06</span><p>Hover the objects to explore</p><i>↓</i></div></section>}

function Title({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy:string}){return <div className="section-title"><p>{index} / 06 &nbsp; {kicker}</p><h1>{title}</h1><span>{copy}</span></div>}
function Graphic(){return <section className="subpage graphic-page"><Title index="02" kicker="DIGITAL SKETCHBOOK" title="Graphic Design" copy="A draggable wall of visual identities, posters and experiments."/><div className="canvas-hint">DRAG TO EXPLORE ↗</div><div className="sketch-canvas">{projects.map((p,i)=><article key={p[0]} className={`poster poster-${i}`}><div className="poster-art"><b>{p[3]}</b><i>{i%2?'NEW / FORM':'MAKE / PLAY'}</i><strong>{p[0]}</strong></div><footer><span>{p[1]}</span><button><Expand size={14}/></button></footer></article>)}</div></section>}
function PGVG({shot,setShot}:{shot:number;setShot:(n:number)=>void}){const scenes=[['SUNDAY LIGHT','Quiet rituals in the city','sun'],['AFTER RAIN','A study of color and reflection','rain'],['SOFT MOTION','Movement, material, memory','motion']];const s=scenes[shot];return <section className="subpage pgvg-page"><Title index="03" kicker="THROUGH THE VIEWFINDER" title="Photo & Video" copy="Short stories framed in light, rhythm and human detail."/><div className={`viewfinder vf-${s[2]}`}><div className="corner tl"/><div className="corner tr"/><div className="corner bl"/><div className="corner br"/><span className="rec">● REC &nbsp; 00:0{shot+2}:18</span><div className="focus">+</div><button className="play"><Play fill="currentColor"/></button><div className="shot-copy"><small>0{shot+1} / 03</small><h2>{s[0]}</h2><p>{s[1]}</p></div></div><div className="camera-controls"><button onClick={()=>setShot((shot+2)%3)}><ChevronLeft/></button><span>ISO 400 &nbsp; · &nbsp; F 2.8 &nbsp; · &nbsp; 1/125</span><button onClick={()=>setShot((shot+1)%3)}><ChevronRight/></button></div></section>}
function Web({format,setFormat}:{format:string;setFormat:(x:string)=>void}){return <section className="subpage web-page"><Title index="04" kicker="SELECTED DIGITAL WORK" title="Web Experiences" copy="Useful interfaces with a little wonder tucked inside."/><div className="device-toggle">{['Desktop','Tablet','Mobile'].map(x=><button className={format===x?'active':''} onClick={()=>setFormat(x)} key={x}>{x}</button>)}</div><div className={`browser-shell ${format.toLowerCase()}`}><div className="browser-bar"><i/><i/><i/><span>mori-studio.example</span></div><div className="browser-site"><header>MORI <b>MENU</b></header><div><small>DESIGN FOR SLOWER DAYS</small><h2>Objects for<br/><em>daily rituals.</em></h2><button>Explore collection ↗</button></div><aside><span>01</span><strong>Stone<br/>lamp</strong></aside></div></div><div className="project-meta"><span>Featured case study — 2026</span><span>Strategy · UX/UI · Creative development</span></div></section>}
function Models({model,setModel}:{model:string;setModel:(x:string)=>void}){return <section className="subpage models-page"><Title index="05" kicker="MINI EXHIBITION" title="3D Modelling" copy="Form studies, playful objects and tiny worlds."/><div className="model-tabs">{['Wireframe','Clay','Final'].map(x=><button className={model===x?'active':''} onClick={()=>setModel(x)} key={x}>{x}</button>)}</div><div className={`gallery-stage ${model.toLowerCase()}`}><div className="pedestal p1"><div className="model blob"/><small>01 &nbsp; Pebble chair</small></div><div className="pedestal p2"><div className="model arch"/><small>02 &nbsp; Portal study</small></div><div className="pedestal p3"><div className="model knot"/><small>03 &nbsp; Soft loop</small></div><p>DRAG TO ROTATE &nbsp; ↻</p></div></section>}
function Lab({prompt,setPrompt,generated,setGenerated}:{prompt:string;setPrompt:(x:string)=>void;generated:boolean;setGenerated:(x:boolean)=>void}){return <section className="subpage lab-page"><Title index="06" kicker="AI CREATIVE LAB" title="AIGC Experiments" copy="From curious prompts to visual systems and moving ideas."/><div className="lab-grid"><div className="prompt-panel"><span className="lab-step">STEP 01 — WRITE A PROMPT</span><textarea value={prompt} onChange={e=>{setPrompt(e.target.value);setGenerated(false)}}/><div className="chips"><button onClick={()=>setPrompt(prompt+', soft clay style')}>+ soft clay</button><button onClick={()=>setPrompt(prompt+', cinematic light')}>+ cinematic</button></div><button className="generate" onClick={()=>setGenerated(true)}><Sparkles size={16}/> Generate idea <Send size={14}/></button></div><div className={`generation ${generated?'done':''}`}><span className="lab-step">STEP 02 — VISUAL OUTPUT</span>{generated?<><div className="ai-scene"><div className="cloud c1"/><div className="cloud c2"/><div className="mini-room"><i>•ᴗ•</i></div></div><p>Concept generated from your prompt.</p></>:<div className="empty-ai"><Sparkles/><p>Your generated world<br/>will appear here.</p></div>}</div></div></section>}
